### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by sweidner2001** [sweidner2001/BCN-2024SS-TeamWeiss-InfluenzaConnect#8]
# Beschreibung
Nur das Frontend-Design

# Aufgaben
- Name
- Geburtsdatum
- Land
- Sprachen
- Email
- Passwort 
- Telefonnr [optional]

## User-Story
![Image](https://github.com/sweidner2001/BCN-2024SS-TeamWeiss-InfluenzaConnect/assets/67543723/ee9a49fe-6599-435b-8d2c-16f0ecb8ac0b)

**Comment by Hemandl** [comment]
Geburtsdatum fehlt noch ( evtl Kalender oder so)
